mnai/LSS-Fahrzeuglisten

- Hamburg/Berufsfeuerwehr_Hamburg.tsv
> HH > BF > Updates aus Issue 18 umgesetzt

- Mecklenburg-Vorpommern/Polizei_Mecklenburg-Vorpommern.txt
> MV -> Pol -> Polizeihubschrauber übertragen

- Niedersachsen/Harburg (WL)/FF_Harburg.tsv
> NI > WL > FF Landkreis Harburg übertragen und aktualisiert

- Bremen/Polizei_Bremerhaven.txt
> HB > BHV > Polizei Bremerhaven übertragen

- Sonderlisten/Kranunternehmen_Hamburg.txt
> Sonderlisten > Kranunternehmen hinzugefügt

- Niedersachsen/Stade (STD)/RD+SEG_Stade.tsv
> NI > STD > RD+SEG Stade übertragen und aktualisiert

- Niedersachsen/Harburg (WL)/FF_Harburg.tsv
> NI > WL > FF > TLF 3000 Ohlendorf, MZF Holm

- Niedersachsen/Stadt Cuxhaven (CUX)/RD+SEG+WR_Stadt_Cuxhaven.tsv
> NI > CUX > RD+SEG+WR Stadt Cuxhaven hinzugefügt

- Niedersachsen/Stade (STD)/FF_Stade.tsv
> NI > STD > FF Stade übertragen und aktualisiert

- Niedersachsen/Rotenburg (ROW)/FF_Rotenburg.tsv
> NI > ROW > FF_Rotenburg übertragen

- Schleswig-Holstein/Neumünster (NMS)/BF+FF+RD+SEG_Neumünster.tsv
> SH > NMS > BF+FF+RD+SEG Neumünster übertragen

- Bremen/RD+SEG_Bremerhaven.tsv
> HB > BHV > RD+SEG Bremerhaven übertragen

- Schleswig-Holstein/Steinburg (IZ)/FF_Steinburg.tsv
> SH > IZ > FF Landkreis Steinburg übertragen

- Schleswig-Holstein/Dithmarschen (HEI)/FF_Dithmarschen.csv
> SH > HEI > FF Landkreis Dithmarschen

- Hamburg/Bereitschaftspolizei_Hamburg.txt
Korrektur leBefKW
Hinzugefügt AAH
Hinzugefügt EZ
> HH > BPOL: leBefKW, AAH, EZ

- Schleswig-Holstein/Steinburg (IZ)/FF_Steinburg.tsv
> SH > IZ > Korrekturen FF Kreis Steinburg

- Niedersachsen/Rotenburg (ROW)/RD+SEG_Rotenburg.tsv
> NI > ROW > RD+SEG Rotenburg übertragen

- Schleswig-Holstein/Steinburg (IZ)/FF_Steinburg.tsv
> SH > IZ > FF Weitere Korrekturen (Wehren 18, 30, 82)

- Niedersachsen/Stade (STD)/FF_Stade.tsv
> NI > STD > FF Ahrenswohlde Anbau ergänzt

- Niedersachsen/Cuxhaven Stadt (CUX)/RD+SEG+WR_Stadt_Cuxhaven.tsv
> NI > CUX > DLRG Cuxhaven Fahrzeugrotation

- Schleswig-Holstein/Lauenburg (RZ)/FF_Lauenburg.tsv
> SH > RZ > FF Herzogtum Lauenburg Neue Liste

- Bremen/BF_Bremen.tsv
- Bremen/FF_Bremen.tsv
- Bremen/Polizei_Bremen.tsv
- Bremen/RD+SEG+WR_Bremen.tsv
- Bremen/RD+SEG+WR_Bremerhaven.tsv
> HB > BF+FF+RD+SEG+WR+Pol Übertragen / neue Listen + BHV WR

- Bremen/THW_Bremen+Bremerhaven.tsv
> HB+BHV > THW Liste übertragen

- Hamburg/Bereitschaftspolizei_Hamburg.txt
- Hamburg/Berufsfeuerwehr_Hamburg.tsv
- Hamburg/Krankentransport_Privat_Hamburg.tsv
- Hamburg/LKA.txt
- Hamburg/Polizei_Hamburg.txt
- Hamburg/Rettungsdienst_HiOrgs_Hamburg.tsv
- Hamburg/SEGs_Hamburg.tsv
- Hamburg/THW_Hamburg.tsv
Closes #73 
Closes #74 
Closes #114
Closes #126 
Closes #127
Closes #129 
Closes #130 
Closes #132
Closes #140 
Closes #141 
Closes #145 
Closes #146 
Closes #148 
Closes #149 
Closes #151 
Closes #152 
Closes #156 
Closes #157 
Closes #158 
Closes #159 
Closes #160 
Closes #161 
Closes #173
> HH > BF, LKA, POL, BePol, RD_HiOrg, SEG, THW

- Nordrhein-Westfalen/Köln/FF_Koeln.csv
- Nordrhein-Westfalen/Köln/Wachkürzel_Kennzahlen_GABs.csv
NRW > K > FF_Koeln hinzugefügt
> NRW > K > FF_Koeln hinzugefügt

- Niedersachsen/THW_Niedersachsen.tsv
> NI > THW Niedersachsen übertragen und aktualisiert

- Schleswig-Holstein/Pinneberg (PI)/RD_Pinneberg.tsv
> SH > PI > Rettungsdienst Pinneberg übertragen und aktualisiert

- Schleswig-Holstein/Segeberg (SE)/RD+SEG+WR_Segeberg.tsv
> SH > SE > RD+SEG+WR Segeberg übertragen und aktualisiert

- Bremen/Leitstellen_Bremen.txt
- Hamburg/Leitstellen_Hamburg.txt
- Niedersachsen/Leitstellen_Niedersachsen.txt
- Schleswig-Holstein/Leitstellen_Schleswig-Holstein.txt
> * > Leitstellen HB HH NI SH hinzugefügt

- Schleswig-Holstein/Kiel (KI)/BF+FF+RD_Kiel.tsv
- Schleswig-Holstein/Kiel (KI)/SEG+WR_Kiel.tsv
> SH > KI > BF+FF+RD+SEG+WR Kiel übertragen und aktualisiert

- Schleswig-Holstein/Stormarn (OD)/FF_Stormarn.tsv
Closes #162 
Closes #163 
Closes #169 
Closes #170 
Closes #184 
Closes #187 
Closes #226
> SH > OD > FF Diverse Korrekturen und Neufahrzeuge

- Sonderlisten/Sonstige_Fahrzeuge.tsv
> Sonderlisten > Sonstige Fahrzeuge ergänzt

- Niedersachsen/Heidekreis (HK)/FF_Heidekreis.tsv
Closes #209 
Closes #219 
Closes #232
> NI > HK > FF Mehrere Neufahrzeuge

- Schleswig-Holstein/Dithmarschen (HEI)/FF_Dithmarschen.csv
closes #202 #221 #262 #264 #265 #266 #267 #268 #269 #270 #271
> SH > HEI: Update FW

- Hamburg/Berufsfeuerwehr_Hamburg.tsv
- Hamburg/Rettungsdienst_HiOrgs_Hamburg.tsv
- Hamburg/SEGs_Hamburg.tsv
Closes #242 
Closes #220 
Closes #216 
Closes #213 
Closes #203 
Closes #201 
Closes #198 
Closes #197
> HH > RD/SEG > Diverse Updates, Korrekturen und Ergänzungen

- Schleswig-Holstein/Dithmarschen (HEI)/FF_Dithmarschen.csv
Closes #291 
Closes #289 
Closes #286 
Closes #284 
Closes #283 
Closes #276 
Closes #271
> SH > HEI > FF Mehrere Korrekturen Feuerwehr LK Dithmarschen

- Niedersachsen/Harburg (WL)/FF_Harburg.tsv
Closes #294 
Closes #252 
Closes #258 
Closes #210
> NI > WL > FF Landkreis Harburg Update

- Bremen/BF_Bremen.tsv
> HB > BF > Eröffnung FuRW 7 + Neuordnung Sonderfahrzeuge

- Schleswig-Holstein/Stormarn (OD)/FF_Stormarn.tsv
Closes #314 
Closes #288
Closes #281 
Closes #280 
Closes #279 
Closes #274
> SH > OD > FF Diverse Updates FF-Fahrzeuge

- Niedersachsen/Rotenburg (ROW)/FF_Rotenburg.tsv
- Niedersachsen/Stade (STD)/FF_Stade.tsv
Closes #295 
Closes #278 
Closes #263 
Closes #285 
Closes #316
> NI > STD+ROW > FF Updates

- Schleswig-Holstein/Steinburg (IZ)/RD+SEG+WR_Steinburg.tsv
> SH > IZ > SEG KTW 25-85-01 hinzugefügt

- Hamburg/Berufsfeuerwehr_Hamburg.tsv
- Hamburg/Rettungsdienst_HiOrgs_Hamburg.tsv
- Hamburg/SEGs_Hamburg.tsv
> HH > BF/RD > Diverse Updates Rettungswagen und BF Hamburg

- Hamburg/Freiwillige_Feuerwehr_Hamburg.tsv
Closes #208 
Closes #257 
Closes #336 
Closes #337 
Closes #338 
Closes #339 
Closes #340 
Closes #341 
Closes #342 
Closes #343 
Closes #344 
Closes #345 
Closes #346
> HH > FF > Neufahrzeuge und neue Wachen

- Schleswig-Holstein/Ostholstein (OH)/RD+SEG+WR_Ostholstein.tsv
> SH > OH > RD+SEG+WR übertragen und aktualisiert

- Schleswig-Holstein/Dithmarschen (HEI)/RD+SEG+WR_Dithmarschen.tsv
> HEI > SEG > mehrere Aktualisierungen

- Schleswig-Holstein/Pinneberg (PI)/FF_Pinneberg.tsv
Closes #68 
Closes #139 
Closes #185 
Closes #355 
Related #290
> SH > PI > FF Landkreis Pinneberg

- Schleswig-Holstein/Nordfriesland (NF)/RD+SEG+WR_Nordfriesland.tsv
> SH > NF > RD+SEG+WR Nordfriesland

- Schleswig-Holstein/Lauenburg (RZ)/FF_Lauenburg.tsv
Closes #240 
Closes #241 
Closes #366 
Closes #368 
Closes #370
> RZ > FF > Diverse Updates

- Schleswig-Holstein/Pinneberg (PI)/FF_Pinneberg.tsv
> SH > PI > FF Kleine Updates

- Schleswig-Holstein/Steinburg (IZ)/FF_Steinburg.tsv
Closes #389
Closes #387
Closes #379
Closes #378
Closes #377
Closes #376
Closes #375
Closes #374
Closes #373
Closes #372
Closes #371
Closes #360
> SH > IZ > FF Diverse Fahrzeugupdates

- Seenotrettung.tsv
> Seenotrettung neue Boote Zingst und Zinnowitz

- Niedersachsen/Stade (STD)/FF_Stade.tsv
- Niedersachsen/Stade (STD)/RD+SEG+WR_Stade.tsv
Closes #211 
Closes #320 
Closes #321 
Closes #347 
Closes #364 
Closes #400
> NI > STD > WR hinzugefügt, FF+RD Update

- Niedersachsen/Lüneburg (LG)/RD+SEG+WR_Lüneburg.tsv
> NI > LG > RD > Update Rettungsdienst
